import fs from 'fs'
import path from 'path'

const RESEARCH_DIR = path.join(process.cwd(), 'research', 'markets')
const PINE_DIR = path.join(process.cwd(), 'research', 'markets', 'pine-script')

// Map keywords to knowledge base files
const KEYWORD_MAP: Record<string, string[]> = {
  // Investors
  buffett: ['investors/buffett-philosophy.md'],
  warren: ['investors/buffett-philosophy.md'],
  moat: ['investors/buffett-philosophy.md'],
  'intrinsic value': ['investors/buffett-philosophy.md', 'analysts/benjamin-graham-complete.md'],
  dalio: ['investors/dalio-philosophy.md'],
  'all weather': ['investors/dalio-philosophy.md'],
  'debt cycle': ['investors/dalio-philosophy.md'],
  'risk parity': ['investors/dalio-philosophy.md'],
  soros: ['investors/soros-philosophy.md'],
  reflexivity: ['investors/soros-philosophy.md'],
  'prevailing bias': ['investors/soros-philosophy.md'],
  bubble: ['investors/soros-philosophy.md', 'analysts/jeremy-grantham-complete.md'],
  tudor: ['investors/tudor-jones-philosophy.md'],
  'paul tudor': ['investors/tudor-jones-philosophy.md'],
  trend: ['investors/tudor-jones-philosophy.md', 'investors/livermore-philosophy.md'],
  'risk management': ['risk/risk-management-rules.md', 'investors/tudor-jones-philosophy.md'],
  lynch: ['investors/lynch-philosophy.md'],
  'peter lynch': ['investors/lynch-philosophy.md'],
  peg: ['investors/lynch-philosophy.md'],
  'ten bagger': ['investors/lynch-philosophy.md'],
  livermore: ['investors/livermore-philosophy.md'],
  'jesse livermore': ['investors/livermore-philosophy.md'],
  'tape reading': ['investors/livermore-philosophy.md', 'technical/order-flow-microstructure.md', 'market-structure/market-structure-complete.md'],
  'pivot point': ['investors/livermore-philosophy.md'],
  'line of least resistance': ['investors/livermore-philosophy.md'],

  // Technical
  candlestick: ['technical/candlestick-patterns.md'],
  doji: ['technical/candlestick-patterns.md'],
  hammer: ['technical/candlestick-patterns.md'],
  engulfing: ['technical/candlestick-patterns.md'],
  'chart pattern': ['technical/chart-patterns.md'],
  'head and shoulders': ['technical/chart-patterns.md'],
  'double top': ['technical/chart-patterns.md'],
  'double bottom': ['technical/chart-patterns.md'],
  'cup and handle': ['technical/chart-patterns.md'],
  'bull flag': ['technical/chart-patterns.md'],
  'bear flag': ['technical/chart-patterns.md'],
  support: ['technical/support-resistance.md'],
  resistance: ['technical/support-resistance.md'],
  vwap: ['technical/support-resistance.md', 'styles/day-trading-complete-guide.md'],
  fibonacci: ['technical/fibonacci-levels.md'],
  fib: ['technical/fibonacci-levels.md'],
  'moving average': ['technical/moving-averages.md'],
  ema: ['technical/moving-averages.md'],
  sma: ['technical/moving-averages.md'],
  '200 day': ['technical/moving-averages.md'],
  rsi: ['technical/momentum-indicators.md'],
  macd: ['technical/momentum-indicators.md'],
  stochastic: ['technical/momentum-indicators.md'],
  momentum: ['technical/momentum-indicators.md'],
  divergence: ['technical/momentum-indicators.md'],
  volume: ['technical/volume-analysis.md'],
  'on balance volume': ['technical/volume-analysis.md'],
  obv: ['technical/volume-analysis.md'],
  'volume profile': ['technical/volume-analysis.md'],
  elliott: ['technical/elliott-wave.md'],
  'elliott wave': ['technical/elliott-wave.md'],
  'wave count': ['technical/elliott-wave.md'],
  'order flow': ['technical/order-flow-microstructure.md'],
  'order block': ['technical/order-flow-microstructure.md', 'technical/smart-money-concepts.md'],
  'smart money': ['technical/order-flow-microstructure.md', 'funds/smart-money-tracking-techniques.md'],
  'dark pool': ['technical/order-flow-microstructure.md', 'data-sources/options-flow-scanners-guide.md'],
  'options flow': ['technical/options-flow-dark-pools.md', 'data-sources/options-flow-scanners-guide.md'],
  'unusual options': ['technical/options-flow-dark-pools.md', 'data-sources/options-flow-scanners-guide.md'],
  gamma: ['technical/options-flow-dark-pools.md'],
  'implied volatility': ['technical/options-flow-dark-pools.md'],
  'iv crush': ['technical/options-flow-dark-pools.md'],
  greeks: ['technical/options-flow-dark-pools.md'],
  delta: ['technical/options-flow-dark-pools.md'],

  // Trading Styles
  scalp: ['styles/scalping-complete-guide.md'],
  scalping: ['styles/scalping-complete-guide.md'],
  'day trade': ['styles/day-trading-complete-guide.md'],
  'day trading': ['styles/day-trading-complete-guide.md'],
  intraday: ['styles/day-trading-complete-guide.md'],
  'opening range': ['styles/day-trading-complete-guide.md'],
  swing: ['styles/swing-trading-complete-guide.md'],
  'swing trade': ['styles/swing-trading-complete-guide.md'],
  position: ['styles/position-trading-complete-guide.md'],
  'long term': ['styles/long-term-investing-complete-guide.md'],
  'dollar cost': ['styles/long-term-investing-complete-guide.md'],
  dca: ['styles/long-term-investing-complete-guide.md'],

  // Funds
  'hedge fund': ['funds/hedge-funds-complete-guide.md'],
  '13f': ['funds/fund-flows-and-market-impact.md', 'data-sources/sec-filings-13f-guide.md'],
  'institutional': ['funds/fund-flows-and-market-impact.md'],
  etf: ['funds/etf-mechanics-and-trading.md'],
  'leveraged etf': ['funds/etf-mechanics-and-trading.md'],
  vix: ['funds/etf-mechanics-and-trading.md'],
  'sector rotation': ['funds/fund-flows-and-market-impact.md'],
  'fund flow': ['funds/fund-flows-and-market-impact.md'],
  cot: ['funds/fund-flows-and-market-impact.md'],
  'commitment of traders': ['funds/fund-flows-and-market-impact.md'],
  activist: ['funds/hedge-funds-complete-guide.md'],
  'window dressing': ['funds/fund-flows-and-market-impact.md'],

  // Analysts
  graham: ['analysts/benjamin-graham-complete.md'],
  'benjamin graham': ['analysts/benjamin-graham-complete.md'],
  'margin of safety': ['analysts/benjamin-graham-complete.md', 'investors/buffett-philosophy.md'],
  'net net': ['analysts/benjamin-graham-complete.md'],
  burry: ['analysts/michael-burry-complete.md'],
  'michael burry': ['analysts/michael-burry-complete.md'],
  subprime: ['analysts/michael-burry-complete.md'],
  damodaran: ['analysts/aswath-damodaran-complete.md'],
  dcf: ['analysts/aswath-damodaran-complete.md'],
  'discounted cash flow': ['analysts/aswath-damodaran-complete.md'],
  wacc: ['analysts/aswath-damodaran-complete.md'],
  whitney: ['analysts/meredith-whitney-complete.md'],
  footnote: ['analysts/meredith-whitney-complete.md'],
  'stress test': ['analysts/meredith-whitney-complete.md'],
  meeker: ['analysts/mary-meeker-complete.md'],
  'mary meeker': ['analysts/mary-meeker-complete.md'],
  's-curve': ['analysts/mary-meeker-complete.md'],
  adoption: ['analysts/mary-meeker-complete.md'],
  blodget: ['analysts/henry-blodget-complete.md'],
  narrative: ['analysts/henry-blodget-complete.md'],
  roubini: ['analysts/nouriel-roubini-complete.md'],
  'systemic risk': ['analysts/nouriel-roubini-complete.md'],
  grantham: ['analysts/jeremy-grantham-complete.md'],
  'mean reversion': ['analysts/jeremy-grantham-complete.md'],
  cape: ['analysts/jeremy-grantham-complete.md'],
  shiller: ['analysts/jeremy-grantham-complete.md'],

  // Risk
  'position sizing': ['risk/position-sizing-formulas.md'],
  'stop loss': ['risk/risk-management-rules.md', 'investors/tudor-jones-philosophy.md'],
  drawdown: ['risk/risk-management-rules.md'],
  psychology: ['risk/trading-psychology.md'],
  fomo: ['risk/trading-psychology.md'],
  'revenge trading': ['risk/trading-psychology.md'],
  journal: ['risk/trading-journal-template.md'],

  // Platforms
  tradingview: ['platforms/tradingview-complete-guide.md'],
  thinkorswim: ['platforms/thinkorswim-complete-guide.md'],
  tos: ['platforms/thinkorswim-complete-guide.md'],
  'level 2': ['platforms/thinkorswim-complete-guide.md', 'market-structure/market-structure-complete.md'],
  scanner: ['platforms/tradingview-complete-guide.md', 'platforms/thinkorswim-complete-guide.md'],

  // ── Crypto Specialists ──────────────────────────────────────────────────────
  saylor: ['../crypto/michael-saylor-bitcoin-thesis.md'],
  microstrategy: ['../crypto/michael-saylor-bitcoin-thesis.md'],
  'corporate bitcoin': ['../crypto/michael-saylor-bitcoin-thesis.md'],
  'bitcoin treasury': ['../crypto/michael-saylor-bitcoin-thesis.md'],
  'bitcoin etf': ['../crypto/michael-saylor-bitcoin-thesis.md'],
  'institutional bitcoin': ['../crypto/michael-saylor-bitcoin-thesis.md'],
  'bitcoin adoption': ['../crypto/michael-saylor-bitcoin-thesis.md', '../crypto/crypto-cycles-complete.md'],

  'cathie wood': ['../crypto/cathie-wood-crypto-framework.md'],
  'ark invest': ['../crypto/cathie-wood-crypto-framework.md'],
  'bitcoin price target': ['../crypto/cathie-wood-crypto-framework.md'],
  'disruptive innovation': ['../crypto/cathie-wood-crypto-framework.md'],
  'bitcoin million': ['../crypto/cathie-wood-crypto-framework.md'],

  'raoul pal': ['../crypto/raoul-pal-macro-crypto.md'],
  'real vision': ['../crypto/raoul-pal-macro-crypto.md'],
  'banana zone': ['../crypto/raoul-pal-macro-crypto.md'],
  'everything code': ['../crypto/raoul-pal-macro-crypto.md'],
  'global m2': ['../crypto/raoul-pal-macro-crypto.md', '../crypto/crypto-macro-correlation.md'],
  'global liquidity': ['../crypto/raoul-pal-macro-crypto.md', '../crypto/crypto-macro-correlation.md'],

  vitalik: ['../crypto/vitalik-buterin-ethereum.md'],
  'ethereum roadmap': ['../crypto/vitalik-buterin-ethereum.md'],
  'proof of stake': ['../crypto/vitalik-buterin-ethereum.md'],
  'blockchain trilemma': ['../crypto/vitalik-buterin-ethereum.md'],
  'ethereum staking': ['../crypto/vitalik-buterin-ethereum.md'],
  'ultra sound money': ['../crypto/vitalik-buterin-ethereum.md'],

  'planb': ['../crypto/planb-stock-to-flow.md'],
  'stock to flow': ['../crypto/planb-stock-to-flow.md'],
  's2f': ['../crypto/planb-stock-to-flow.md'],
  'mvrv': ['../crypto/planb-stock-to-flow.md', '../crypto/on-chain-analysis-complete.md'],
  'realized price': ['../crypto/planb-stock-to-flow.md', '../crypto/on-chain-analysis-complete.md'],
  halving: ['../crypto/planb-stock-to-flow.md', '../crypto/crypto-cycles-complete.md'],
  'thermocap': ['../crypto/planb-stock-to-flow.md'],

  'arthur hayes': ['../crypto/arthur-hayes-derivatives-macro.md'],
  'funding rate': ['../crypto/arthur-hayes-derivatives-macro.md'],
  'open interest': ['../crypto/arthur-hayes-derivatives-macro.md'],
  'yen carry': ['../crypto/arthur-hayes-derivatives-macro.md', '../crypto/crypto-macro-correlation.md'],
  liquidation: ['../crypto/arthur-hayes-derivatives-macro.md'],
  'crypto derivatives': ['../crypto/arthur-hayes-derivatives-macro.md'],
  'basis trade': ['../crypto/arthur-hayes-derivatives-macro.md'],
  'perpetual futures': ['../crypto/arthur-hayes-derivatives-macro.md', '../crypto/crypto-perps-trading.md'],
  perps: ['../crypto/arthur-hayes-derivatives-macro.md'],

  'andreas antonopoulos': ['../crypto/andreas-antonopoulos-bitcoin-fundamentals.md'],
  'mastering bitcoin': ['../crypto/andreas-antonopoulos-bitcoin-fundamentals.md'],
  'not your keys': ['../crypto/andreas-antonopoulos-bitcoin-fundamentals.md'],
  'self custody': ['../crypto/andreas-antonopoulos-bitcoin-fundamentals.md'],
  'lightning network': ['../crypto/andreas-antonopoulos-bitcoin-fundamentals.md'],
  'hash rate': ['../crypto/andreas-antonopoulos-bitcoin-fundamentals.md', '../crypto/on-chain-analysis-complete.md'],
  'bitcoin network': ['../crypto/andreas-antonopoulos-bitcoin-fundamentals.md'],

  hoskinson: ['../crypto/charles-hoskinson-cardano-governance.md'],
  cardano: ['../crypto/charles-hoskinson-cardano-governance.md'],
  '\bada\b': ['../crypto/charles-hoskinson-cardano-governance.md'],
  iohk: ['../crypto/charles-hoskinson-cardano-governance.md'],
  ouroboros: ['../crypto/charles-hoskinson-cardano-governance.md'],
  'formal verification': ['../crypto/charles-hoskinson-cardano-governance.md'],
  'blockchain governance': ['../crypto/charles-hoskinson-cardano-governance.md'],

  // ── Crypto Topics ────────────────────────────────────────────────────────────
  'on chain': ['../crypto/on-chain-analysis-complete.md'],
  'on-chain': ['../crypto/on-chain-analysis-complete.md'],
  'exchange inflow': ['../crypto/on-chain-analysis-complete.md'],
  'exchange outflow': ['../crypto/on-chain-analysis-complete.md'],
  'exchange reserve': ['../crypto/on-chain-analysis-complete.md'],
  sopr: ['../crypto/on-chain-analysis-complete.md'],
  'long term holder': ['../crypto/on-chain-analysis-complete.md'],
  'short term holder': ['../crypto/on-chain-analysis-complete.md'],
  'miner': ['../crypto/on-chain-analysis-complete.md'],
  'nvt': ['../crypto/on-chain-analysis-complete.md'],
  'puell': ['../crypto/on-chain-analysis-complete.md'],

  'crypto cycle': ['../crypto/crypto-cycles-complete.md'],
  'bitcoin cycle': ['../crypto/crypto-cycles-complete.md'],
  'bull market crypto': ['../crypto/crypto-cycles-complete.md'],
  'bear market crypto': ['../crypto/crypto-cycles-complete.md'],
  'crypto bear': ['../crypto/crypto-cycles-complete.md'],
  'crypto bull': ['../crypto/crypto-cycles-complete.md'],
  'fear greed': ['../crypto/crypto-cycles-complete.md'],
  'btc dominance': ['../crypto/crypto-cycles-complete.md', '../crypto/altcoin-season-mechanics.md'],

  'altcoin season': ['../crypto/altcoin-season-mechanics.md'],
  'altcoin': ['../crypto/altcoin-season-mechanics.md'],
  'alt season': ['../crypto/altcoin-season-mechanics.md'],
  'bitcoin dominance': ['../crypto/altcoin-season-mechanics.md'],

  defi: ['../crypto/defi-complete-guide.md'],
  'total value locked': ['../crypto/defi-complete-guide.md'],
  tvl: ['../crypto/defi-complete-guide.md'],
  uniswap: ['../crypto/defi-complete-guide.md'],
  aave: ['../crypto/defi-complete-guide.md'],
  lido: ['../crypto/defi-complete-guide.md'],
  'yield farming': ['../crypto/defi-complete-guide.md'],
  'liquidity pool': ['../crypto/defi-complete-guide.md', 'technical/smart-money-concepts.md'],
  'liquid staking': ['../crypto/defi-complete-guide.md'],
  'decentralized exchange': ['../crypto/defi-complete-guide.md'],
  dex: ['../crypto/defi-complete-guide.md'],

  'layer 2': ['../crypto/layer2-scaling-solutions.md'],
  'layer2': ['../crypto/layer2-scaling-solutions.md'],
  '\bl2\b': ['../crypto/layer2-scaling-solutions.md'],
  arbitrum: ['../crypto/layer2-scaling-solutions.md'],
  'optimism': ['../crypto/layer2-scaling-solutions.md'],
  'base chain': ['../crypto/layer2-scaling-solutions.md'],
  zksync: ['../crypto/layer2-scaling-solutions.md'],
  starknet: ['../crypto/layer2-scaling-solutions.md'],
  rollup: ['../crypto/layer2-scaling-solutions.md'],
  'zk rollup': ['../crypto/layer2-scaling-solutions.md'],
  'optimistic rollup': ['../crypto/layer2-scaling-solutions.md'],

  'crypto macro': ['../crypto/crypto-macro-correlation.md'],
  'crypto correlation': ['../crypto/crypto-macro-correlation.md'],
  dxy: ['../crypto/crypto-macro-correlation.md'],
  'm2 money': ['../crypto/crypto-macro-correlation.md'],
  'stablecoin supply': ['../crypto/crypto-macro-correlation.md'],

  // ── Macro / Fed ──────────────────────────────────────────────────────────────
  'fed': ['macro/fed-macro-complete.md'],
  'federal reserve': ['macro/fed-macro-complete.md'],
  'fomc': ['macro/fed-macro-complete.md'],
  'interest rate': ['macro/fed-macro-complete.md'],
  'rate hike': ['macro/fed-macro-complete.md'],
  'rate cut': ['macro/fed-macro-complete.md'],
  'dot plot': ['macro/fed-macro-complete.md'],
  'quantitative easing': ['macro/fed-macro-complete.md'],
  'quantitative tightening': ['macro/fed-macro-complete.md'],
  'qe': ['macro/fed-macro-complete.md'],
  'qt': ['macro/fed-macro-complete.md'],
  'yield curve': ['macro/fed-macro-complete.md'],
  'inverted yield': ['macro/fed-macro-complete.md'],
  '2s10s': ['macro/fed-macro-complete.md'],
  'recession': ['macro/fed-macro-complete.md'],
  'inflation': ['macro/fed-macro-complete.md'],
  'cpi': ['macro/fed-macro-complete.md'],
  'pce': ['macro/fed-macro-complete.md'],
  'core inflation': ['macro/fed-macro-complete.md'],
  'tips': ['macro/fed-macro-complete.md'],
  'gdp': ['macro/fed-macro-complete.md'],
  'pmi': ['macro/fed-macro-complete.md'],
  'jobs report': ['macro/fed-macro-complete.md'],
  'nonfarm payroll': ['macro/fed-macro-complete.md'],
  'unemployment': ['macro/fed-macro-complete.md'],
  'fiscal policy': ['macro/fed-macro-complete.md'],
  'monetary policy': ['macro/fed-macro-complete.md'],
  'macro': ['macro/fed-macro-complete.md'],
  'fed funds': ['macro/fed-macro-complete.md'],
  'jerome powell': ['macro/fed-macro-complete.md'],
  'treasury yield': ['macro/fed-macro-complete.md'],
  '10 year': ['macro/fed-macro-complete.md'],
  'bond market': ['macro/fed-macro-complete.md'],
  'geopolitical': ['macro/fed-macro-complete.md'],
  'sahm rule': ['macro/fed-macro-complete.md'],
  'term premium': ['macro/fed-macro-complete.md'],

  // ── Options Strategies ────────────────────────────────────────────────────
  'iron condor': ['options/options-strategies-complete.md'],
  'iron butterfly': ['options/options-strategies-complete.md'],
  'straddle': ['options/options-strategies-complete.md'],
  'strangle': ['options/options-strategies-complete.md'],
  'covered call': ['options/options-strategies-complete.md'],
  'cash secured put': ['options/options-strategies-complete.md', 'options/options-income-wheel.md'],
  'bull call spread': ['options/options-strategies-complete.md'],
  'bear put spread': ['options/options-strategies-complete.md'],
  'calendar spread': ['options/options-strategies-complete.md'],
  'diagonal spread': ['options/options-strategies-complete.md'],
  'leaps': ['options/options-strategies-complete.md'],
  'protective put': ['options/options-strategies-complete.md'],
  'vertical spread': ['options/options-strategies-complete.md'],
  'options strategy': ['options/options-strategies-complete.md'],
  'options strategies': ['options/options-strategies-complete.md'],
  'iv rank': ['options/options-strategies-complete.md'],
  'iv percentile': ['options/options-strategies-complete.md'],
  'theta decay': ['options/options-strategies-complete.md'],
  'rolling options': ['options/options-strategies-complete.md'],
  'expected move': ['options/options-strategies-complete.md'],
  'poor mans covered call': ['options/options-strategies-complete.md'],

  // ── Sector Analysis ───────────────────────────────────────────────────────
  'sector': ['sectors/sector-rotation-complete.md'],
  'sector analysis': ['sectors/sector-rotation-complete.md'],
  'xlk': ['sectors/sector-rotation-complete.md'],
  'xlv': ['sectors/sector-rotation-complete.md'],
  'xlf': ['sectors/sector-rotation-complete.md'],
  'xle': ['sectors/sector-rotation-complete.md'],
  'xly': ['sectors/sector-rotation-complete.md'],
  'xlp': ['sectors/sector-rotation-complete.md'],
  'xli': ['sectors/sector-rotation-complete.md'],
  'xlb': ['sectors/sector-rotation-complete.md'],
  'xlre': ['sectors/sector-rotation-complete.md'],
  'xlu': ['sectors/sector-rotation-complete.md'],
  'xlc': ['sectors/sector-rotation-complete.md'],
  'technology sector': ['sectors/sector-rotation-complete.md'],
  'healthcare sector': ['sectors/sector-rotation-complete.md'],
  'financial sector': ['sectors/sector-rotation-complete.md'],
  'energy sector': ['sectors/sector-rotation-complete.md'],
  'semiconductor': ['sectors/sector-rotation-complete.md'],
  'biotech': ['sectors/sector-rotation-complete.md'],
  'reit': ['sectors/sector-rotation-complete.md'],
  'rule of 40': ['sectors/sector-rotation-complete.md'],
  'cap rate': ['sectors/sector-rotation-complete.md'],
  'patent cliff': ['sectors/sector-rotation-complete.md'],

  // ── Earnings Analysis ─────────────────────────────────────────────────────
  'earnings': ['earnings/earnings-analysis-complete.md'],
  'earnings report': ['earnings/earnings-analysis-complete.md'],
  'earnings call': ['earnings/earnings-analysis-complete.md'],
  'eps': ['earnings/earnings-analysis-complete.md'],
  'earnings beat': ['earnings/earnings-analysis-complete.md'],
  'earnings miss': ['earnings/earnings-analysis-complete.md'],
  'guidance': ['earnings/earnings-analysis-complete.md'],
  'whisper number': ['earnings/earnings-analysis-complete.md'],
  'estimate revision': ['earnings/earnings-analysis-complete.md'],
  'earnings season': ['earnings/earnings-analysis-complete.md'],
  '10-q': ['earnings/earnings-analysis-complete.md', 'data-sources/sec-filings-13f-guide.md'],
  '10-k': ['earnings/earnings-analysis-complete.md', 'data-sources/sec-filings-13f-guide.md'],
  '8-k': ['earnings/earnings-analysis-complete.md'],
  'same store sales': ['earnings/earnings-analysis-complete.md'],
  'arr': ['earnings/earnings-analysis-complete.md'],
  'nrr': ['earnings/earnings-analysis-complete.md'],
  'channel check': ['earnings/earnings-analysis-complete.md'],
  'alternative data': ['earnings/earnings-analysis-complete.md'],
  'ebitda': ['earnings/earnings-analysis-complete.md'],
  'free cash flow': ['earnings/earnings-analysis-complete.md'],
  'gross margin': ['earnings/earnings-analysis-complete.md'],

  // ── International Markets & Forex ─────────────────────────────────────────
  'forex': ['international/international-markets-complete.md'],
  'currency': ['international/international-markets-complete.md'],
  'eur/usd': ['international/international-markets-complete.md'],
  'eurusd': ['international/international-markets-complete.md'],
  'usd/jpy': ['international/international-markets-complete.md'],
  'usdjpy': ['international/international-markets-complete.md'],
  'gbp/usd': ['international/international-markets-complete.md'],
  'gbpusd': ['international/international-markets-complete.md'],
  'aud/usd': ['international/international-markets-complete.md'],
  'carry trade': ['international/international-markets-complete.md', '../crypto/arthur-hayes-derivatives-macro.md'],
  'boj': ['international/international-markets-complete.md'],
  'ecb': ['international/international-markets-complete.md'],
  'nikkei': ['international/international-markets-complete.md'],
  'dax': ['international/international-markets-complete.md'],
  'ftse': ['international/international-markets-complete.md'],
  'shanghai': ['international/international-markets-complete.md'],
  'emerging markets': ['international/international-markets-complete.md'],
  'em': ['international/international-markets-complete.md'],
  'china market': ['international/international-markets-complete.md'],
  'pboc': ['international/international-markets-complete.md'],
  'japan': ['international/international-markets-complete.md'],
  'europe market': ['international/international-markets-complete.md'],
  'adr': ['international/international-markets-complete.md'],
  'de-dollarization': ['international/international-markets-complete.md'],
  'brics': ['international/international-markets-complete.md'],
  'international': ['international/international-markets-complete.md'],

  // ── Commodities ───────────────────────────────────────────────────────────
  'gold': ['commodities/commodities-complete.md'],
  'silver': ['commodities/commodities-complete.md'],
  'oil': ['commodities/commodities-complete.md'],
  'crude oil': ['commodities/commodities-complete.md'],
  'wti': ['commodities/commodities-complete.md'],
  'brent': ['commodities/commodities-complete.md'],
  'opec': ['commodities/commodities-complete.md'],
  'copper': ['commodities/commodities-complete.md'],
  'commodity': ['commodities/commodities-complete.md'],
  'commodities': ['commodities/commodities-complete.md'],
  'natural gas': ['commodities/commodities-complete.md'],
  'wheat': ['commodities/commodities-complete.md'],
  'corn': ['commodities/commodities-complete.md'],
  'soybeans': ['commodities/commodities-complete.md'],
  'agricultural': ['commodities/commodities-complete.md'],
  'commodity supercycle': ['commodities/commodities-complete.md'],
  'precious metals': ['commodities/commodities-complete.md'],
  'gold miners': ['commodities/commodities-complete.md'],
  'gld': ['commodities/commodities-complete.md'],
  'uso': ['commodities/commodities-complete.md'],
  'crack spread': ['commodities/commodities-complete.md'],
  'eia': ['commodities/commodities-complete.md'],
  'royalty company': ['commodities/commodities-complete.md'],

  // ── Fixed Income / Bonds ──────────────────────────────────────────────────
  'bond': ['fixed-income/fixed-income-complete.md'],
  'bonds': ['fixed-income/fixed-income-complete.md'],
  'fixed income': ['fixed-income/fixed-income-complete.md'],
  'treasury': ['fixed-income/fixed-income-complete.md'],
  'treasuries': ['fixed-income/fixed-income-complete.md'],
  'tlt': ['fixed-income/fixed-income-complete.md'],
  'agg': ['fixed-income/fixed-income-complete.md'],
  'duration': ['fixed-income/fixed-income-complete.md'],
  'convexity': ['fixed-income/fixed-income-complete.md'],
  'credit spread': ['fixed-income/fixed-income-complete.md'],
  'high yield': ['fixed-income/fixed-income-complete.md'],
  'investment grade': ['fixed-income/fixed-income-complete.md'],
  'hyg': ['fixed-income/fixed-income-complete.md'],
  'lqd': ['fixed-income/fixed-income-complete.md'],
  'muni': ['fixed-income/fixed-income-complete.md'],
  'municipal bond': ['fixed-income/fixed-income-complete.md'],
  'corporate bond': ['fixed-income/fixed-income-complete.md'],
  'mbs': ['fixed-income/fixed-income-complete.md'],
  'mortgage backed': ['fixed-income/fixed-income-complete.md'],
  'credit default swap': ['fixed-income/fixed-income-complete.md'],
  'cds': ['fixed-income/fixed-income-complete.md'],
  'fallen angel': ['fixed-income/fixed-income-complete.md'],
  'steepener': ['fixed-income/fixed-income-complete.md'],
  'flattener': ['fixed-income/fixed-income-complete.md'],
  'ytm': ['fixed-income/fixed-income-complete.md'],
  'i bond': ['fixed-income/fixed-income-complete.md'],

  // ── Futures ───────────────────────────────────────────────────────────────
  'futures': ['futures/futures-complete.md'],
  'futures contract': ['futures/futures-complete.md'],
  '/es': ['futures/futures-complete.md'],
  '/nq': ['futures/futures-complete.md'],
  'es futures': ['futures/futures-complete.md'],
  'nq futures': ['futures/futures-complete.md'],
  'spy futures': ['futures/futures-complete.md'],
  'e-mini': ['futures/futures-complete.md'],
  'emini': ['futures/futures-complete.md'],
  'micro futures': ['futures/futures-complete.md'],
  '/cl': ['futures/futures-complete.md'],
  '/gc': ['futures/futures-complete.md'],
  'treasury futures': ['futures/futures-complete.md'],
  'zb': ['futures/futures-complete.md'],
  'zn': ['futures/futures-complete.md'],
  'contango': ['futures/futures-complete.md', 'commodities/commodities-complete.md'],
  'backwardation': ['futures/futures-complete.md', 'commodities/commodities-complete.md'],
  'roll yield': ['futures/futures-complete.md'],
  'mark to market': ['futures/futures-complete.md'],
  'initial margin': ['futures/futures-complete.md'],
  'maintenance margin': ['futures/futures-complete.md'],
  'span margin': ['futures/futures-complete.md'],
  'calendar spread futures': ['futures/futures-complete.md'],
  'section 1256': ['futures/futures-complete.md', 'tax/tax-strategy-complete.md'],

  // ── Short Selling ─────────────────────────────────────────────────────────
  'short selling': ['short-selling/short-selling-complete.md'],
  'short sell': ['short-selling/short-selling-complete.md'],
  'short interest': ['short-selling/short-selling-complete.md'],
  'days to cover': ['short-selling/short-selling-complete.md'],
  'short squeeze': ['short-selling/short-selling-complete.md'],
  'gamma squeeze': ['short-selling/short-selling-complete.md'],
  'hard to borrow': ['short-selling/short-selling-complete.md'],
  'borrow rate': ['short-selling/short-selling-complete.md'],
  'uptick rule': ['short-selling/short-selling-complete.md'],
  'naked short': ['short-selling/short-selling-complete.md'],
  'chanos': ['short-selling/short-selling-complete.md'],
  'muddy waters': ['short-selling/short-selling-complete.md'],
  'hindenburg': ['short-selling/short-selling-complete.md'],
  'citron': ['short-selling/short-selling-complete.md'],
  'short report': ['short-selling/short-selling-complete.md'],
  'inverse etf': ['short-selling/short-selling-complete.md'],
  'locate': ['short-selling/short-selling-complete.md'],

  // ── Smart Money Concepts ──────────────────────────────────────────────────
  'smart money concepts': ['technical/smart-money-concepts.md'],
  'smc': ['technical/smart-money-concepts.md'],
  'fair value gap': ['technical/smart-money-concepts.md'],
  'fvg': ['technical/smart-money-concepts.md'],
  'breaker block': ['technical/smart-money-concepts.md'],
  'liquidity sweep': ['technical/smart-money-concepts.md'],
  'stop hunt': ['technical/smart-money-concepts.md'],
  'change of character': ['technical/smart-money-concepts.md'],
  'choch': ['technical/smart-money-concepts.md'],
  'break of structure': ['technical/smart-money-concepts.md'],
  'bos': ['technical/smart-money-concepts.md'],
  'premium zone': ['technical/smart-money-concepts.md'],
  'discount zone': ['technical/smart-money-concepts.md'],
  'inducement': ['technical/smart-money-concepts.md'],
  'killzone': ['technical/smart-money-concepts.md'],
  'kill zone': ['technical/smart-money-concepts.md'],
  'ict': ['technical/smart-money-concepts.md'],
  'inner circle trader': ['technical/smart-money-concepts.md'],
  'equal highs': ['technical/smart-money-concepts.md'],
  'equal lows': ['technical/smart-money-concepts.md'],
  'optimal trade entry': ['technical/smart-money-concepts.md'],
  'ote': ['technical/smart-money-concepts.md'],

  // ── Portfolio Construction ────────────────────────────────────────────────
  'portfolio': ['portfolio/portfolio-construction-complete.md'],
  'portfolio construction': ['portfolio/portfolio-construction-complete.md'],
  'asset allocation': ['portfolio/portfolio-construction-complete.md'],
  'diversification': ['portfolio/portfolio-construction-complete.md'],
  'sharpe ratio': ['portfolio/portfolio-construction-complete.md'],
  'sortino ratio': ['portfolio/portfolio-construction-complete.md'],
  'calmar ratio': ['portfolio/portfolio-construction-complete.md'],
  'efficient frontier': ['portfolio/portfolio-construction-complete.md'],
  'modern portfolio theory': ['portfolio/portfolio-construction-complete.md'],
  'mpt': ['portfolio/portfolio-construction-complete.md'],
  'factor investing': ['portfolio/portfolio-construction-complete.md'],
  'rebalancing': ['portfolio/portfolio-construction-complete.md'],
  'max drawdown': ['portfolio/portfolio-construction-complete.md'],
  'tail risk': ['portfolio/portfolio-construction-complete.md'],
  'correlation': ['portfolio/portfolio-construction-complete.md'],
  'kelly criterion': ['portfolio/portfolio-construction-complete.md'],
  'permanent portfolio': ['portfolio/portfolio-construction-complete.md'],
  'endowment model': ['portfolio/portfolio-construction-complete.md'],
  'performance attribution': ['portfolio/portfolio-construction-complete.md'],
  'alpha': ['portfolio/portfolio-construction-complete.md'],
  'beta': ['portfolio/portfolio-construction-complete.md'],

  // ── Options Income / Wheel ────────────────────────────────────────────────
  'wheel strategy': ['options/options-income-wheel.md'],
  'the wheel': ['options/options-income-wheel.md'],
  'jade lizard': ['options/options-income-wheel.md'],
  'tasty trade': ['options/options-income-wheel.md'],
  'tastytrade': ['options/options-income-wheel.md'],
  'theta income': ['options/options-income-wheel.md'],
  'premium selling': ['options/options-income-wheel.md'],
  'selling options': ['options/options-income-wheel.md'],
  'options income': ['options/options-income-wheel.md'],
  'credit received': ['options/options-income-wheel.md'],
  'probability of profit': ['options/options-income-wheel.md'],
  'pop': ['options/options-income-wheel.md'],

  // ── Tax Strategy ──────────────────────────────────────────────────────────
  'tax': ['tax/tax-strategy-complete.md'],
  'taxes': ['tax/tax-strategy-complete.md'],
  'capital gains': ['tax/tax-strategy-complete.md'],
  'tax loss harvesting': ['tax/tax-strategy-complete.md'],
  'wash sale': ['tax/tax-strategy-complete.md'],
  'roth ira': ['tax/tax-strategy-complete.md'],
  'traditional ira': ['tax/tax-strategy-complete.md'],
  'ira': ['tax/tax-strategy-complete.md'],
  '401k': ['tax/tax-strategy-complete.md'],
  'backdoor roth': ['tax/tax-strategy-complete.md'],
  'qualified dividend': ['tax/tax-strategy-complete.md'],
  'tax efficient': ['tax/tax-strategy-complete.md'],
  'step up basis': ['tax/tax-strategy-complete.md'],
  'donor advised fund': ['tax/tax-strategy-complete.md'],
  'crypto tax': ['tax/tax-strategy-complete.md'],
  'short term gain': ['tax/tax-strategy-complete.md'],
  'long term gain': ['tax/tax-strategy-complete.md'],
  'niit': ['tax/tax-strategy-complete.md'],
  'net investment income': ['tax/tax-strategy-complete.md'],

  // ── Market Structure ──────────────────────────────────────────────────────
  'market structure': ['market-structure/market-structure-complete.md'],
  'market maker': ['market-structure/market-structure-complete.md'],
  'payment for order flow': ['market-structure/market-structure-complete.md'],
  'pfof': ['market-structure/market-structure-complete.md'],
  'hft': ['market-structure/market-structure-complete.md'],
  'high frequency trading': ['market-structure/market-structure-complete.md'],
  'order routing': ['market-structure/market-structure-complete.md'],
  'bid ask': ['market-structure/market-structure-complete.md'],
  'time and sales': ['market-structure/market-structure-complete.md'],
  'pre market': ['market-structure/market-structure-complete.md'],
  'after hours': ['market-structure/market-structure-complete.md'],
  'regnms': ['market-structure/market-structure-complete.md'],
  'iex': ['market-structure/market-structure-complete.md'],
  'spoofing': ['market-structure/market-structure-complete.md'],
  'iceberg order': ['market-structure/market-structure-complete.md'],
  'moc': ['market-structure/market-structure-complete.md'],
  'moo': ['market-structure/market-structure-complete.md'],
  'ats': ['market-structure/market-structure-complete.md'],

  // ── Backtesting ───────────────────────────────────────────────────────────
  'backtest': ['backtesting/backtesting-complete.md'],
  'backtesting': ['backtesting/backtesting-complete.md'],
  'back test': ['backtesting/backtesting-complete.md'],
  'curve fitting': ['backtesting/backtesting-complete.md'],
  'overfitting': ['backtesting/backtesting-complete.md'],
  'walk forward': ['backtesting/backtesting-complete.md'],
  'survivorship bias': ['backtesting/backtesting-complete.md'],
  'look ahead bias': ['backtesting/backtesting-complete.md'],
  'paper trading': ['backtesting/backtesting-complete.md'],
  'strategy tester': ['backtesting/backtesting-complete.md'],
  'profit factor': ['backtesting/backtesting-complete.md'],
  'expectancy': ['backtesting/backtesting-complete.md'],
  'monte carlo': ['backtesting/backtesting-complete.md'],
  'vectorbt': ['backtesting/backtesting-complete.md'],
  'quantconnect': ['backtesting/backtesting-complete.md'],
  'zipline': ['backtesting/backtesting-complete.md'],

  // ── Special Situations / Merger Arb ──────────────────────────────────────
  'merger arbitrage': ['special-situations/special-situations-complete.md'],
  'merger arb': ['special-situations/special-situations-complete.md'],
  'special situation': ['special-situations/special-situations-complete.md'],
  'spinoff': ['special-situations/special-situations-complete.md'],
  'spin off': ['special-situations/special-situations-complete.md'],
  'spin-off': ['special-situations/special-situations-complete.md'],
  'spac': ['special-situations/special-situations-complete.md'],
  'bankruptcy': ['special-situations/special-situations-complete.md'],
  'distressed': ['special-situations/special-situations-complete.md'],
  'fulcrum security': ['special-situations/special-situations-complete.md'],
  'rights offering': ['special-situations/special-situations-complete.md'],
  'carve out': ['special-situations/special-situations-complete.md'],
  'going private': ['special-situations/special-situations-complete.md'],
  'lbo': ['special-situations/special-situations-complete.md'],
  'tender offer': ['special-situations/special-situations-complete.md'],
  'arbitrage spread': ['special-situations/special-situations-complete.md'],
  'deal spread': ['special-situations/special-situations-complete.md'],
  'hostile takeover': ['special-situations/special-situations-complete.md'],
  'greenblatt': ['special-situations/special-situations-complete.md'],

  // ── New Crypto Topics (2026 expansion) ────────────────────────────────────

  // Bitcoin ETF Mechanics
  'ibit': ['../crypto/bitcoin-etf-mechanics.md'],
  'fbtc': ['../crypto/bitcoin-etf-mechanics.md'],
  'bitb': ['../crypto/bitcoin-etf-mechanics.md'],
  'gbtc': ['../crypto/bitcoin-etf-mechanics.md'],
  'arkb': ['../crypto/bitcoin-etf-mechanics.md'],
  'bitcoin spot etf': ['../crypto/bitcoin-etf-mechanics.md'],
  'ethereum etf': ['../crypto/bitcoin-etf-mechanics.md'],
  'etha': ['../crypto/bitcoin-etf-mechanics.md'],
  'feth': ['../crypto/bitcoin-etf-mechanics.md'],
  'authorized participant': ['../crypto/bitcoin-etf-mechanics.md'],
  'creation redemption': ['../crypto/bitcoin-etf-mechanics.md'],
  'nav premium': ['../crypto/bitcoin-etf-mechanics.md'],
  'nav discount': ['../crypto/bitcoin-etf-mechanics.md'],
  'bitcoin etf flows': ['../crypto/bitcoin-etf-mechanics.md'],
  'crypto etf': ['../crypto/bitcoin-etf-mechanics.md'],
  'blackrock bitcoin': ['../crypto/bitcoin-etf-mechanics.md'],

  // Crypto Self-Custody & Security
  'hardware wallet': ['../crypto/crypto-security-custody.md'],
  'ledger': ['../crypto/crypto-security-custody.md'],
  'trezor': ['../crypto/crypto-security-custody.md'],
  'coldcard': ['../crypto/crypto-security-custody.md'],
  'seed phrase': ['../crypto/crypto-security-custody.md'],
  'private key': ['../crypto/crypto-security-custody.md'],
  'cold storage': ['../crypto/crypto-security-custody.md'],
  'multisig': ['../crypto/crypto-security-custody.md'],
  'multi-signature': ['../crypto/crypto-security-custody.md'],
  'crypto custody': ['../crypto/crypto-security-custody.md'],
  'crypto wallet': ['../crypto/crypto-security-custody.md'],
  'phantom wallet': ['../crypto/crypto-security-custody.md'],
  'metamask': ['../crypto/crypto-security-custody.md'],
  'crypto hack': ['../crypto/crypto-security-custody.md'],
  'crypto security': ['../crypto/crypto-security-custody.md'],
  'hot wallet': ['../crypto/crypto-security-custody.md'],
  'air gap': ['../crypto/crypto-security-custody.md'],
  'psbt': ['../crypto/crypto-security-custody.md'],
  'ftx collapse': ['../crypto/crypto-security-custody.md'],
  'not your keys not your coins': ['../crypto/crypto-security-custody.md'],

  // Memecoins
  'memecoin': ['../crypto/memecoins-complete.md'],
  'memecoins': ['../crypto/memecoins-complete.md'],
  'doge': ['../crypto/memecoins-complete.md'],
  'dogecoin': ['../crypto/memecoins-complete.md'],
  'shiba': ['../crypto/memecoins-complete.md'],
  'shib': ['../crypto/memecoins-complete.md'],
  'pepe': ['../crypto/memecoins-complete.md'],
  'floki': ['../crypto/memecoins-complete.md'],
  'bonk': ['../crypto/memecoins-complete.md'],
  'wif': ['../crypto/memecoins-complete.md'],
  'pump.fun': ['../crypto/memecoins-complete.md'],
  'pumpfun': ['../crypto/memecoins-complete.md'],
  'meme token': ['../crypto/memecoins-complete.md'],
  'solana meme': ['../crypto/memecoins-complete.md'],
  'rug pull': ['../crypto/memecoins-complete.md'],
  'degen': ['../crypto/memecoins-complete.md'],
  'sniper bot': ['../crypto/memecoins-complete.md'],
  'copy trade': ['../crypto/memecoins-complete.md'],
  'fresh wallet': ['../crypto/memecoins-complete.md'],

  // Crypto Portfolio Management
  'crypto portfolio': ['../crypto/crypto-portfolio-management.md'],
  'crypto allocation': ['../crypto/crypto-portfolio-management.md'],
  'bitcoin allocation': ['../crypto/crypto-portfolio-management.md'],
  'crypto rebalancing': ['../crypto/crypto-portfolio-management.md'],
  'crypto position sizing': ['../crypto/crypto-portfolio-management.md'],
  'crypto dca': ['../crypto/crypto-portfolio-management.md'],
  'crypto barbell': ['../crypto/crypto-portfolio-management.md'],
  'bitcoin percentage': ['../crypto/crypto-portfolio-management.md'],
  'crypto risk management': ['../crypto/crypto-portfolio-management.md'],
  'altcoin allocation': ['../crypto/crypto-portfolio-management.md'],
  'take profit crypto': ['../crypto/crypto-portfolio-management.md'],
  'stablecoin reserve': ['../crypto/crypto-portfolio-management.md', '../crypto/stablecoins-complete.md'],
  'sat accumulation': ['../crypto/crypto-portfolio-management.md'],

  // Crypto Perps / Perpetual Futures
  'perp trading': ['../crypto/crypto-perps-trading.md'],
  'crypto leverage': ['../crypto/crypto-perps-trading.md'],
  'cross margin': ['../crypto/crypto-perps-trading.md'],
  'isolated margin': ['../crypto/crypto-perps-trading.md'],
  'liquidation price': ['../crypto/crypto-perps-trading.md'],
  'mark price': ['../crypto/crypto-perps-trading.md'],
  'index price': ['../crypto/crypto-perps-trading.md'],
  'bybit': ['../crypto/crypto-perps-trading.md'],
  'binance futures': ['../crypto/crypto-perps-trading.md'],
  'hyperliquid': ['../crypto/crypto-perps-trading.md'],
  'dydx': ['../crypto/crypto-perps-trading.md'],
  'gmx': ['../crypto/crypto-perps-trading.md'],
  'long short ratio': ['../crypto/crypto-perps-trading.md'],
  'top trader ratio': ['../crypto/crypto-perps-trading.md'],
  'crypto basis trade': ['../crypto/crypto-perps-trading.md'],
  'delta neutral crypto': ['../crypto/crypto-perps-trading.md'],
  'cash and carry crypto': ['../crypto/crypto-perps-trading.md'],

  // Crypto Options (already has crypto-options-complete.md from previous session)
  'crypto options': ['../crypto/crypto-options-complete.md'],
  'deribit': ['../crypto/crypto-options-complete.md'],
  'bitcoin options': ['../crypto/crypto-options-complete.md'],
  'ethereum options': ['../crypto/crypto-options-complete.md'],
  'crypto iv': ['../crypto/crypto-options-complete.md'],
  'dvol': ['../crypto/crypto-options-complete.md'],
  'crypto covered call': ['../crypto/crypto-options-complete.md'],
  'crypto put': ['../crypto/crypto-options-complete.md'],
  'crypto call': ['../crypto/crypto-options-complete.md'],
  'max pain crypto': ['../crypto/crypto-options-complete.md'],
  'gamma exposure crypto': ['../crypto/crypto-options-complete.md'],
  'options expiry crypto': ['../crypto/crypto-options-complete.md'],

  // Solana Ecosystem
  'solana': ['../crypto/solana-ecosystem-complete.md'],
  'sol': ['../crypto/solana-ecosystem-complete.md'],
  'solana ecosystem': ['../crypto/solana-ecosystem-complete.md'],
  'solana dex': ['../crypto/solana-ecosystem-complete.md'],
  'jupiter': ['../crypto/solana-ecosystem-complete.md'],
  'raydium': ['../crypto/solana-ecosystem-complete.md'],
  'jito': ['../crypto/solana-ecosystem-complete.md'],
  'mev solana': ['../crypto/solana-ecosystem-complete.md'],
  'solana validator': ['../crypto/solana-ecosystem-complete.md'],
  'solana staking': ['../crypto/solana-ecosystem-complete.md'],
  'solana nft': ['../crypto/solana-ecosystem-complete.md'],
  'magic eden': ['../crypto/solana-ecosystem-complete.md'],
  'tensor': ['../crypto/solana-ecosystem-complete.md'],
  'proof of history': ['../crypto/solana-ecosystem-complete.md'],

  // Stablecoins
  'stablecoin': ['../crypto/stablecoins-complete.md'],
  'stablecoins': ['../crypto/stablecoins-complete.md'],
  'usdc': ['../crypto/stablecoins-complete.md'],
  'usdt': ['../crypto/stablecoins-complete.md'],
  'tether': ['../crypto/stablecoins-complete.md'],
  'dai': ['../crypto/stablecoins-complete.md'],
  'frax': ['../crypto/stablecoins-complete.md'],
  'pyusd': ['../crypto/stablecoins-complete.md'],
  'algorithmic stablecoin': ['../crypto/stablecoins-complete.md'],
  'terra luna': ['../crypto/stablecoins-complete.md'],
  'ust collapse': ['../crypto/stablecoins-complete.md'],
  'depeg': ['../crypto/stablecoins-complete.md'],
  'stablecoin yield': ['../crypto/stablecoins-complete.md'],

  // CEX / DEX Exchanges
  'crypto exchange': ['../crypto/exchanges-cex-dex-complete.md'],
  'centralized exchange': ['../crypto/exchanges-cex-dex-complete.md'],
  'cex': ['../crypto/exchanges-cex-dex-complete.md'],
  'binance': ['../crypto/exchanges-cex-dex-complete.md'],
  'coinbase': ['../crypto/exchanges-cex-dex-complete.md'],
  'kraken': ['../crypto/exchanges-cex-dex-complete.md'],
  'okx': ['../crypto/exchanges-cex-dex-complete.md'],
  'exchange liquidity': ['../crypto/exchanges-cex-dex-complete.md'],
  'maker fee': ['../crypto/exchanges-cex-dex-complete.md'],
  'taker fee': ['../crypto/exchanges-cex-dex-complete.md'],
  'amm': ['../crypto/exchanges-cex-dex-complete.md'],
  'automated market maker': ['../crypto/exchanges-cex-dex-complete.md'],
  'impermanent loss': ['../crypto/exchanges-cex-dex-complete.md'],
  'order book dex': ['../crypto/exchanges-cex-dex-complete.md'],
  'aggregator': ['../crypto/exchanges-cex-dex-complete.md'],
  'proof of reserves': ['../crypto/exchanges-cex-dex-complete.md'],
  'merkle proof': ['../crypto/exchanges-cex-dex-complete.md'],

  // Real World Assets (RWA)
  'real world asset': ['../crypto/rwa-complete.md'],
  'rwa': ['../crypto/rwa-complete.md'],
  'tokenized asset': ['../crypto/rwa-complete.md'],
  'tokenized treasury': ['../crypto/rwa-complete.md'],
  'ondo': ['../crypto/rwa-complete.md'],
  'maple finance': ['../crypto/rwa-complete.md'],
  'tokenized gold': ['../crypto/rwa-complete.md'],
  'paxg': ['../crypto/rwa-complete.md'],
  'tokenized real estate': ['../crypto/rwa-complete.md'],
  'on-chain treasury': ['../crypto/rwa-complete.md'],
  'private credit crypto': ['../crypto/rwa-complete.md'],
  'centrifuge': ['../crypto/rwa-complete.md'],

  // Data sources
  barchart: ['data-sources/options-flow-scanners-guide.md'],
  'unusual whales': ['data-sources/options-flow-scanners-guide.md'],
  finviz: ['data-sources/options-flow-scanners-guide.md'],
  '10k': ['data-sources/sec-filings-13f-guide.md'],
  'sec filing': ['data-sources/sec-filings-13f-guide.md'],
  'form 4': ['data-sources/sec-filings-13f-guide.md'],
  insider: ['data-sources/sec-filings-13f-guide.md'],
  'whalewisdom': ['data-sources/sec-filings-13f-guide.md'],
}

// Pine Script keyword → file mapping (based on LLM_MANIFEST.md)
const PINE_KEYWORD_MAP: Record<string, string[]> = {
  // Execution & core concepts
  'barstate': ['concepts/execution_model.md'],
  'var ': ['concepts/execution_model.md'],
  'varip': ['concepts/execution_model.md'],
  'calc_on_every_tick': ['concepts/execution_model.md'],
  'execution model': ['concepts/execution_model.md'],
  'bar-by-bar': ['concepts/execution_model.md'],
  'repainting': ['concepts/timeframes.md'],
  'request.security': ['concepts/timeframes.md'],
  'multi-timeframe': ['concepts/timeframes.md'],
  'mtf': ['concepts/timeframes.md'],
  'htf': ['concepts/timeframes.md'],
  'color.new': ['concepts/colors_and_display.md'],
  'bgcolor': ['concepts/colors_and_display.md'],
  'color.from_gradient': ['concepts/colors_and_display.md'],
  'common error': ['concepts/common_errors.md'],
  'compile error': ['concepts/common_errors.md'],
  'series string': ['concepts/common_errors.md'],
  'undeclared identifier': ['concepts/common_errors.md'],
  'max_bars_back': ['concepts/common_errors.md'],
  // Reference
  'syminfo': ['reference/variables.md'],
  'bar_index': ['reference/variables.md'],
  'built-in variable': ['reference/variables.md'],
  'color.red': ['reference/constants.md'],
  'shape.triangle': ['reference/constants.md'],
  'plot.style': ['reference/constants.md'],
  'alert.freq': ['reference/constants.md'],
  'simple int': ['reference/types.md'],
  'series float': ['reference/types.md'],
  'type casting': ['reference/types.md'],
  'switch': ['reference/keywords.md'],
  'export': ['reference/keywords.md'],
  'import': ['reference/keywords.md'],
  // Functions by namespace
  'ta.': ['reference/functions/ta.md'],
  'ta.ema': ['reference/functions/ta.md'],
  'ta.rsi': ['reference/functions/ta.md'],
  'ta.macd': ['reference/functions/ta.md'],
  'ta.sma': ['reference/functions/ta.md'],
  'ta.bb': ['reference/functions/ta.md'],
  'ta.atr': ['reference/functions/ta.md'],
  'ta.stoch': ['reference/functions/ta.md'],
  'ta.vwap': ['reference/functions/ta.md'],
  'ta.cross': ['reference/functions/ta.md'],
  'ta.highest': ['reference/functions/ta.md'],
  'ta.lowest': ['reference/functions/ta.md'],
  'ta.pivothigh': ['reference/functions/ta.md'],
  'ta.pivotlow': ['reference/functions/ta.md'],
  'strategy.entry': ['reference/functions/strategy.md'],
  'strategy.exit': ['reference/functions/strategy.md'],
  'strategy.close': ['reference/functions/strategy.md'],
  'strategy.order': ['reference/functions/strategy.md'],
  'strategy(': ['reference/functions/strategy.md'],
  'commission': ['reference/functions/strategy.md'],
  'slippage': ['reference/functions/strategy.md'],
  'pyramiding': ['reference/functions/strategy.md'],
  'request.': ['reference/functions/request.md'],
  'array.': ['reference/functions/collections.md'],
  'matrix.': ['reference/functions/collections.md'],
  'map.': ['reference/functions/collections.md'],
  'line.new': ['reference/functions/drawing.md'],
  'label.new': ['reference/functions/drawing.md'],
  'box.new': ['reference/functions/drawing.md'],
  'table.new': ['reference/functions/drawing.md'],
  'polyline': ['reference/functions/drawing.md'],
  'plot(': ['reference/functions/general.md'],
  'plotshape': ['reference/functions/general.md'],
  'plotchar': ['reference/functions/general.md'],
  'fill(': ['reference/functions/general.md'],
  'hline': ['reference/functions/general.md'],
  'alertcondition': ['reference/functions/general.md'],
  // Methods & objects
  'method ': ['concepts/methods.md'],
  '.new(': ['concepts/objects.md'],
  'user-defined type': ['concepts/objects.md'],
  'udt': ['concepts/objects.md'],
  // Writing scripts
  'debug': ['writing_scripts/debugging.md'],
  'profil': ['writing_scripts/profiling_and_optimization.md'],
  'optimiz': ['writing_scripts/profiling_and_optimization.md'],
  'limitation': ['writing_scripts/limitations.md'],
  'style guide': ['writing_scripts/style_guide.md'],
  'publish': ['writing_scripts/publishing_scripts.md'],
}

function readFile(filePath: string): string {
  try {
    // Support ../crypto/ prefix for crypto knowledge base files
    const fullPath = filePath.startsWith('../crypto/')
      ? path.join(RESEARCH_DIR, '..', 'markets', 'crypto', filePath.replace('../crypto/', ''))
      : path.join(RESEARCH_DIR, filePath)
    if (fs.existsSync(fullPath)) {
      return fs.readFileSync(fullPath, 'utf-8')
    }
  } catch {
    // file not found
  }
  return ''
}

function readPineFile(relativePath: string): string {
  try {
    const fullPath = path.join(PINE_DIR, relativePath)
    if (fs.existsSync(fullPath)) {
      return fs.readFileSync(fullPath, 'utf-8')
    }
  } catch {}
  return ''
}

export function getRelevantPineKnowledge(userMessage: string): string {
  const message = userMessage.toLowerCase()
  const filesToLoad = new Set<string>()

  for (const [keyword, files] of Object.entries(PINE_KEYWORD_MAP)) {
    if (message.includes(keyword.toLowerCase())) {
      files.forEach(f => filesToLoad.add(f))
    }
  }

  // If it's a pine script question but no specific keyword matched, load the complete reference
  const isPineQuestion = /pine\s*script|indicator\(|strategy\(|@version\s*=\s*[56]|tradingview\s*script/i.test(userMessage)
  if (isPineQuestion && filesToLoad.size === 0) {
    // Load the complete reference (it's 400KB — only do this as fallback)
    filesToLoad.add('pinescriptv6_complete_reference.md')
  }

  const contents: string[] = []
  for (const file of Array.from(filesToLoad).slice(0, 5)) {
    const content = readPineFile(file)
    if (content) {
      const name = path.basename(file, '.md').replace(/-/g, ' ').toUpperCase()
      contents.push(`\n\n---\n## PINE SCRIPT v6 DOCS: ${name}\n\n${content}`)
    }
  }

  return contents.join('')
}

export function getSystemPrompt(): string {
  const systemPromptPath = path.join(RESEARCH_DIR, 'SYSTEM-PROMPT.md')
  try {
    return fs.readFileSync(systemPromptPath, 'utf-8')
  } catch {
    return 'You are The Investment Council, a personal market intelligence agent.'
  }
}

export function getRelevantKnowledge(userMessage: string): string {
  const message = userMessage.toLowerCase()
  const filesToLoad = new Set<string>()

  // Match keywords to relevant files
  for (const [keyword, files] of Object.entries(KEYWORD_MAP)) {
    if (message.includes(keyword)) {
      files.forEach(f => filesToLoad.add(f))
    }
  }

  // If nothing matched, load only risk management as a lightweight default
  // Do NOT auto-load council framework files — those are only loaded when explicitly requested
  if (filesToLoad.size === 0) {
    filesToLoad.add('risk/risk-management-rules.md')
  }

  // Cap at 4 files to keep context manageable and response fast
  const limitedFiles = Array.from(filesToLoad).slice(0, 4)

  const contents: string[] = []
  for (const file of limitedFiles) {
    const content = readFile(file)
    if (content) {
      const fileName = path.basename(file, '.md').replace(/-/g, ' ').toUpperCase()
      contents.push(`\n\n---\n## KNOWLEDGE BASE: ${fileName}\n\n${content}`)
    }
  }

  return contents.join('')
}
